# Generated by Django 4.2 on 2024-07-05 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('depression_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depressiontestattempt',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
