# Generated by Django 4.2 on 2024-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audio/'),
        ),
    ]
