
# Generated by Django 4.2.6 on 2024-06-21 20:03

from django.db import migrations

from django.db import migrations

def populate_user_progress(apps, schema_editor):
    UserProgress = apps.get_model('learning', 'UserProgress')
    Lesson = apps.get_model('learning', 'Lesson')
    CustomUser = apps.get_model('authentication', 'CustomUser')

    lessons = Lesson.objects.all()
    users = CustomUser.objects.all()

    for user in users:
        for lesson in lessons:
            UserProgress.objects.create(user=user, lesson=lesson, read=False)

class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),  # Update with your last migration
    ]

    operations = [
        migrations.RunPython(populate_user_progress),
    ]