# Generated by Django 5.0.3 on 2024-06-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeThinkingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('explanation', models.TextField()),
                ('tips', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('thinking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.negativethinkingtype')),
            ],
        ),
    ]
