# Generated by Django 5.0.3 on 2024-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_cbtquestion_is_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='after_question_tip',
            field=models.TextField(blank=True),
        ),
    ]
