# Generated by Django 4.2 on 2024-07-05 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeaspect',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
