# Generated by Django 5.0.3 on 2024-06-15 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_alter_lifeaspect_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeaspect',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
