# Generated by Django 4.2 on 2024-07-05 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_alter_lifeaspect_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeaspect',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
