# Generated by Django 4.2 on 2024-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_alter_lifeaspect_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeaspect',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
