# Generated by Django 5.0.3 on 2024-06-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0004_lifeaspect_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('aspect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='weekly.lifeaspecttype')),
            ],
        ),
    ]
