# Generated by Django 5.0.3 on 2024-06-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0006_lifeactivitytrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeactivity',
            name='icon',
        ),
    ]
