# Generated by Django 5.0.3 on 2024-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_alter_meditation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
