# Generated by Django 4.2.6 on 2023-11-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_moodthirdentry_moodprimaryentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emotion',
        ),
        migrations.RemoveField(
            model_name='moodthirdentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='MoodPrimaryEntry',
        ),
        migrations.DeleteModel(
            name='MoodThirdEntry',
        ),
    ]
