# Generated by Django 4.2.6 on 2024-03-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_moodprimaryentry_moodsecondentry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodprimaryentry',
            old_name='emotion',
            new_name='mood',
        ),
        migrations.RenameField(
            model_name='moodsecondentry',
            old_name='emotion',
            new_name='mood',
        ),
    ]
