# Generated by Django 4.2.6 on 2024-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_activity_reason_tag_usertags_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='option1',
            field=models.CharField(default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='preference',
            name='option2',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
