# Generated by Django 4.2.6 on 2024-04-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_reasonentry_activityentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsStress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.emotion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.tag')),
            ],
        ),
    ]
