# Generated by Django 4.2.6 on 2024-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_tipsstress_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='emotion',
            field=models.CharField(max_length=100),
        ),
    ]
