# Generated by Django 4.2.6 on 2024-06-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_tips_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='has_depression',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='has_stress',
            field=models.BooleanField(default=True),
        ),
    ]
