# Generated by Django 4.2.6 on 2024-06-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_journalentry_has_depression_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
