# Generated by Django 5.0.4 on 2024-06-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
