# Generated by Django 5.0.4 on 2024-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_userdepactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
