# Generated by Django 5.0.4 on 2024-07-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_useractivity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
