# Generated by Django 5.0.4 on 2024-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_userdepactivity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
